import Head from 'next/head'
import Link from 'next/link'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nasdash</title>
        <meta name="description" content="Generated by Create-Next-App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}
